### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by sergey-shpak** [vikramthyagarajan/node-excel-stream#10]
The example of writing stream is wrong
```js
let writer = new ExcelWriter({
  // ...
});
let dataPromises = inputs.map((input) => {
    // 'tests' is the key of the sheet. That is used
    // to add data to only the Test Sheet
    writer.addData('tests', input);
});
Promise.all(dataPromises)
.then(() => {
    return writer.save();
})
.then((stream) => {
    stream.pipe(fs.createWriteStream('data.xlsx'));
});
```
all the input data is stored in memory (high memory usage) until promise is resolved, 
correct example is:
```js
let writer = new ExcelWriter({
  // ...
});
// write newly added data to file not memory 
writer.pipe(fs.createWriteStream('data.xlsx'))

let dataPromises = inputs.map((input) => {
    // 'tests' is the key of the sheet. That is used
    // to add data to only the Test Sheet
    writer.addData('tests', input);
});
Promise.all(dataPromises)
.then(() => writer.save())
```

**Comment by sergey-shpak** [comment]
but correct example won't work because `exceljs` requires building workbook in memory
> The File I/O documented above requires that an entire workbook is built up in memory before the file can be written. While convenient, it can limit the size of the document due to the amount of memory required.

as result using streams doesn't make any sense in general

**Comment by vikramthyagarajan** [comment]
Understood. The examples are outdated considering the new api of exceljs, will try to redo them.

As to your other point, the literal next line after the one you've quoted from the docs explains that it is more memory efficient.

> A streaming writer (or reader) processes the workbook or worksheet data as it is generated, converting it into file form as it goes. Typically this is much more efficient on memory as the final memory footprint and even intermediate memory footprints are much more compact than with the document version, especially when you consider that the row and cell objects are disposed once they are committed.

**Comment by vikramthyagarajan** [comment]
Actually, now that I read through the PR that bumped up the version where the api changed but the ExcelWriter is abstracted out so no change should show to the end user. I think the example is alright. I think we could do with a more complex example involving a read stream (maybe data from a file) piped to the excel writer instead of writing it from an in memory variable, but this one is simple enough to understand, and is still more efficient than writing the excel with the whole workbook in memory

But you're right, I'll add in a disclaimer like-

> This example is for explanation purposes, the code can more memory efficient if the input data is not in memory and provided via stream that is read and committed to workbook without all of the data being in memory at once

**Comment by vikramthyagarajan** [comment]
Let me know your thoughts, I'm closing this for now. Will reopen incase further changes are required
